In [50]:
from scipy.io import loadmat
import pandas as pd
import numpy as np

In [56]:
mat = loadmat('/home/vladushked/datasets/mpii/mpii_human_pose_v1_u12_2/mpii_human_pose_v1_u12_1.mat',squeeze_me=False)

In [121]:
mpii = {n: mat['RELEASE'][n][0,0] for n in mat['RELEASE'].dtype.names}

In [202]:
mpii.keys()

dict_keys(['annolist', 'img_train', 'version', 'single_person', 'act', 'video_list'])

Number of images

In [224]:
joint_num = 16
img_num = len(mpii['annolist']['image'][0])
img_id = 4

In [268]:
mpii['annolist']['image'][0][0]['name'][0][0][0]

'037454012.jpg'

Массив аннотаций для каждого изображения

In [161]:
len(mpii['annolist']['annorect'][0])

24987

Acts

In [283]:
mpii['act'][951]['cat_name'][0][0]
mpii['img_train'][0][img_id]
mpii['act'][img_id]['act_name'][0].size

1

In [301]:
np.random.choice(np.arange(0, 2), p=[0.5, 0.5])

1

In [300]:
num = 0
for i in range(img_num) :
    if mpii['act'][i]['act_name'][0].size > 0:
        if 'water' in mpii['act'][i]['cat_name'][0][0] and mpii['img_train'][0][i] == 1:
            num += 1
num

1066

In [281]:
num = 0
for i in range(img_num) :
    if mpii['act'][i]['act_name'][0].size > 0:
        if 'div' in mpii['act'][i]['act_name'][0][0]:
            num += 1
            print(mpii['act'][i]['cat_name'][0][0], '|', mpii['act'][i]['act_name'][0][0], '|', mpii['act'][i]['act_id'][0][0][0], '|', mpii['annolist']['image'][0][i]['name'][0][0][0], '|', mpii['img_train'][0][i])
            if (mpii['img_train'][0][i] == 0):
                print('fuck')
                break
num

occupation | skindiving or SCUBA diving as a frogman, Navy Seal | 62 | 062755808.jpg | 1
occupation | skindiving or SCUBA diving as a frogman, Navy Seal | 62 | 058431431.jpg | 1
occupation | skindiving or SCUBA diving as a frogman, Navy Seal | 62 | 090115801.jpg | 1
occupation | skindiving or SCUBA diving as a frogman, Navy Seal | 62 | 004544638.jpg | 1
occupation | skindiving or SCUBA diving as a frogman, Navy Seal | 62 | 028096319.jpg | 1
occupation | skindiving or SCUBA diving as a frogman, Navy Seal | 62 | 095041148.jpg | 1
occupation | skindiving or SCUBA diving as a frogman, Navy Seal | 62 | 089026378.jpg | 1
occupation | skindiving or SCUBA diving as a frogman, Navy Seal | 62 | 045565675.jpg | 1
occupation | skindiving or SCUBA diving as a frogman, Navy Seal | 62 | 062013260.jpg | 1
occupation | skindiving or SCUBA diving as a frogman, Navy Seal | 62 | 027738118.jpg | 1
occupation | skindiving or SCUBA diving as a frogman, Navy Seal | 62 | 038855810.jpg | 1
occupation | skindivi

136

Image name

In [162]:
mpii['annolist'][0][img_id]['image']['name'][0,0][0]

'018283778.jpg'

Массив поз на одном изображении

In [163]:
len(mpii['annolist'][0][img_id]['annorect'][0])

1

In [196]:
mpii['annolist'][0][img_id]['annorect'][0][0] is None

True

Annotations

In [199]:
mpii['annolist'][0][img_id]['annorect'][0][0]['annopoints']

array([[(array([[(array([[610]], dtype=uint16), array([[187]], dtype=uint8), array([[6]], dtype=uint8), array([[0]], dtype=uint8)),
                (array([[647]], dtype=uint16), array([[176]], dtype=uint8), array([[7]], dtype=uint8), array([[1]], dtype=uint8)),
                (array([[637.0201]]), array([[189.8183]]), array([[8]], dtype=uint8), array([], shape=(0, 0), dtype=uint8)),
                (array([[695.9799]]), array([[108.1817]]), array([[9]], dtype=uint8), array([], shape=(0, 0), dtype=uint8)),
                (array([[620]], dtype=uint16), array([[394]], dtype=uint16), array([[0]], dtype=uint8), array([[1]], dtype=uint8)),
                (array([[616]], dtype=uint16), array([[269]], dtype=uint16), array([[1]], dtype=uint8), array([[1]], dtype=uint8)),
                (array([[573]], dtype=uint16), array([[185]], dtype=uint8), array([[2]], dtype=uint8), array([[1]], dtype=uint8)),
                (array([[647]], dtype=uint16), array([[188]], dtype=uint8), array([[3]], dty

Точка

In [149]:
mpii['annolist'][0][img_id]['annorect'][0][0]['annopoints']["point"][0][0].shape

(1, 11)

Количество точек

In [152]:
len(mpii['annolist'][0][img_id]['annorect'][0][0]['annopoints']["point"][0][0][0])

16

Coordinates

In [157]:
mpii['annolist'][0][img_id]['annorect'][0][0]['annopoints']["point"][0][0][0][5]['id'][0][0]

1

Train or test assignment

In [91]:
RELEASE['img_train'][0]

array([0, 0, 0, ..., 1, 0, 0], dtype=uint8)

Check empty annotations

In [90]:
def check_empty(list, name):
    try:
        list[name]
    except ValueError:
        return True

    if len(list[name]) > 0:
        return False
    else:
        return True


In [ ]:
def getData(dataset, dataset_type='train'):
    coco = {'images': [], 'categories': [], 'annotations': []}
    # idx, cat_name, act_name, act_id
    datasetList = []
    datasetSize = dataset['annolist'].shape[1]
    for i in range(datasetSize):
        if ((dataset_type == 'train' and dataset['img_train'][0][i] == 1) or (dataset_type == 'test' and dataset['img_train'][0][i] == 0)) and check_empty(dataset['annolist'][0][i],'annorect') == False: #any person is annotated
            

        name = dataset['annolist']['image'][0][i]['name'][0,0][0]
        img_train = list(dataset['img_train'][0][i])
        single_person = 
        act = [dataset['act']['cat_name'][0][0], dataset['act']['act_name'][0][0], dataset['act']['act_id'][0][0]]
        yield [i, act]